---
# tasks file for wordpress

  - name: Download and unarchive latest WordPress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "/var/www"
      remote_src: yes
      creates: "/var/www/{{ nginx_site_path }}" 
      mode: '0755'
    become: true

  - name: Set owner www-data
    file:
        path: "/var/www/{{ nginx_site_path }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
    become: true
  
    #  - name: Generating index.html
    #    template:
    #      src: 'index.j2'
    #      dest: '/var/www/{{ nginx_site_path }}/index.html'
    #      mode: '0755'
    #    notify: Reload nginx config
    #    become: true
      
  - name: Generating wp-config.php
    template:
      src: 'wp-config.php.j2'
      dest: '/var/www/{{ nginx_site_path }}/wp-config.php'
      mode: '0755'
    notify: Reload nginx config
    become: true
